# Generated by Django 2.2.23 on 2021-05-26 19:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOPSProvider",
            fields=[
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_sops.sopsprovider_set+",
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.Project", verbose_name="Project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AWSKMS",
            fields=[
                (
                    "sopsprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sops.SOPSProvider",
                    ),
                ),
                ("access_key", models.TextField()),
                ("secret_access_key", models.TextField()),
            ],
            options={
                "verbose_name": "AWS KMS Credential",
                "verbose_name_plural": "AWS KMS Credentials",
            },
            bases=("sops.sopsprovider",),
        ),
        migrations.CreateModel(
            name="PGPKey",
            fields=[
                (
                    "sopsprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sops.SOPSProvider",
                    ),
                ),
                ("private_key", models.TextField()),
            ],
            options={
                "verbose_name": "PGP Private Key",
                "verbose_name_plural": "PGP Private Keys",
            },
            bases=("sops.sopsprovider",),
        ),
    ]
