# Generated by Django 2.2.23 on 2021-05-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sops", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="sops_credentials",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="sops.SOPSProvider"
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="decks", to="projects.Project"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together={("deck", "type")},
        ),
    ]
