# Generated by Django 2.2.23 on 2021-06-01 19:15

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20210526_1927"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelmOverrides",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overrides", django.contrib.postgres.fields.jsonb.JSONField(verbose_name="overrides")),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helm_overrides",
                        to="projects.Project",
                        verbose_name="Environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("port", models.PositiveIntegerField(default=61335, verbose_name="Port")),
                ("provider", models.CharField(choices=[("k3d", "k3d")], max_length=255, verbose_name="K8S Provider")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_settings",
                        to="projects.Project",
                        verbose_name="Project",
                    ),
                ),
            ],
        ),
    ]
