# Generated by Django 2.2.23 on 2021-06-01 19:15

from django.db import migrations

from projects.models import Project


def forwards_func(apps, schema_editor):

    for instance in Project.objects.all():
        if not hasattr(instance, "cluster_settings"):
            instance.add_cluster_settings()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_clustersettings_helmoverrides"),
    ]

    operations = [migrations.RunPython(forwards_func)]
