# Generated by Django 2.2.24 on 2021-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_environment_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="spec_type",
            field=models.CharField(choices=[("helm", "Helm")], max_length=5, verbose_name="Type"),
        ),
    ]
