# Generated by Django 2.2.24 on 2021-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_auto_20210628_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="value_schema",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="helmoverrides",
            name="overrides",
            field=models.TextField(verbose_name="overrides"),
        ),
        migrations.AlterField(
            model_name="helmoverrides",
            name="environment",
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE,
                related_name="helm_overrides",
                to="projects.Environment",
                verbose_name="Environment",
            ),
        ),
    ]
