# Generated by Django 2.2.27 on 2022-02-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_helm_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
        migrations.AlterField(
            model_name="project",
            name="spec_type",
            field=models.CharField(
                choices=[("helm", "Helm"), ("plain", "Plain"), ("kustomize", "Kustomize")],
                max_length=5,
                verbose_name="Type",
            ),
        ),
    ]
