name: "Test"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        curl https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar xvz && sudo mv linux-amd64/helm /usr/local/bin/helm

    - name: Test with django tests
      working-directory: ./src
      run: |
        coverage run manage.py test
        coverage report
      env:
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_NAME: github_actions
        DATABASE_HOST: 127.0.0.1
        DJANGO_SETTINGS_MODULE: configuration.settings.test
        KEYCLOAK_SCHEME: http
        KEYCLOAK_HOST: 127.0.0.1
        KEYCLOAK_PORT: 8091
        KEYCLOAK_REALM_NAME: unikube
        KEYCLOAK_CLIENT_ID: projects
        KEYCLOAK_CLIENT_SECRET: e5fd5b49-64bf-42fa-88b4-f879a5d567dc
    - name: Upload coverage data to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
      working-directory: ./src
      run: |
        coveralls --service=github
  coveralls:
    name: Indicate completion to coveralls.io
    # need secrets.GITHUB_TOKEN
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}